name: plant_location_chooser
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.4.0
  fluttertoast: ^8.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "./icon.png"
  min_sdk_android: 19
